#!/bin/bash

#generate keys for nginx
# SSL has not been configured for nginx - to force generation of keys, uncomment the following lines:
#docker run -it --rm --name obis_openssl \
#  -v /Users/byakodpramod/ga_dir/obis/config/ssl/nginx:/sslnginx:z \
#  cybercom/openssl ./sslnginx/generate

#generate keys for message broker, mongodb, and clients
docker run -it --rm --name obis_openssl \
  -v /Users/byakodpramod/ga_dir/obis/config/ssl/backend:/ssl \
  cybercom/openssl ./ssl/generate

